# Makefile for ODZIP

CC      := gcc
CFLAGS  := -std=c17 -O2 -Wall -Wextra -pedantic -march=native -flto
LDFLAGS := -flto
TARGET  := odz

LIB_SRC := odz_util.c bitstream.c huffman.c lz_hashchain.c compress.c decompress.c
LIB_OBJ := $(LIB_SRC:.c=.o)

.PHONY: all clean run

all: libodzip.a $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

libodzip.a: $(LIB_OBJ)
	$(AR) rcs $@ $^

$(TARGET): main.o libodzip.a
	$(CC) $(CFLAGS) -o $@ main.o -L. -lodzip $(LDFLAGS)

run: $(TARGET)
	./$(TARGET) c LICENSE output.odz
	./$(TARGET) d output.odz roundtrip
	cmp LICENSE roundtrip

clean:
	$(RM) $(TARGET) *.o *.a output.odz roundtrip
